# Generated by Django 3.2.4 on 2021-06-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
