# Generated by Django 3.2.4 on 2021-06-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_publishers'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], max_length=255, null=True),
        ),
    ]
