# Generated by Django 3.2.4 on 2021-06-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-title',)},
        ),
    ]
